// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetOptions():Promise<main.Options>;

export function Greet(arg1:string):Promise<string>;

export function HandleImageToPDF(arg1:Array<string>):Promise<string>;

export function SelectFile(arg1:string):Promise<Array<string>>;

export function SelectSavePath():Promise<string>;

export function SetOptions(arg1:main.Options):Promise<void>;
