// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDNS() {
  return window['go']['main']['App']['CheckDNS']();
}

export function CheckLatency() {
  return window['go']['main']['App']['CheckLatency']();
}

export function CheckSpeed() {
  return window['go']['main']['App']['CheckSpeed']();
}

export function GetOptions() {
  return window['go']['main']['App']['GetOptions']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SetOptions(arg1) {
  return window['go']['main']['App']['SetOptions'](arg1);
}
