// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckDNS():Promise<Array<string>>;

export function CheckLatency():Promise<Array<number>>;

export function CheckSpeed():Promise<number>;

export function GetOptions():Promise<main.Options>;

export function Greet(arg1:string):Promise<string>;

export function SetOptions(arg1:main.Options):Promise<void>;
