// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOptions() {
  return window['go']['main']['App']['GetOptions']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HandleImageToPDF(arg1) {
  return window['go']['main']['App']['HandleImageToPDF'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function SelectSavePath() {
  return window['go']['main']['App']['SelectSavePath']();
}

export function SetOptions(arg1) {
  return window['go']['main']['App']['SetOptions'](arg1);
}
